name: reviewdog
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: DominuS-RU/Detekt-Action@master
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
